
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SUP.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeType
{

    public EmployeeType()
    {

        this.Employees = new HashSet<Employee>();

    }


    public System.Guid Id { get; set; }

    public string Title { get; set; }

    public int Salary { get; set; }



    public virtual ICollection<Employee> Employees { get; set; }

}

}
