
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SUP.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Project
{

    public Project()
    {

        this.ProjectWorks = new HashSet<ProjectWork>();

        this.Tasks = new HashSet<Task>();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsRemoved { get; set; }



    public virtual ICollection<ProjectWork> ProjectWorks { get; set; }

    public virtual ICollection<Task> Tasks { get; set; }

}

}
