

//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SUP.Repository
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SUPEntities : DbContext
{
    public SUPEntities()
        : base("name=SUPEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Employee> Employees { get; set; }

    public DbSet<EmployeeType> EmployeeTypes { get; set; }

    public DbSet<Project> Projects { get; set; }

    public DbSet<ProjectWork> ProjectWorks { get; set; }

    public DbSet<sysdiagram> sysdiagrams { get; set; }

    public DbSet<Task> Tasks { get; set; }

    public DbSet<TaskState> TaskStates { get; set; }

    public DbSet<Vacation> Vacations { get; set; }

}

}

