
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SUP.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Task
{

    public System.Guid Id { get; set; }

    public System.Guid ProjectId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public Nullable<System.Guid> PerformerId { get; set; }

    public Nullable<System.Guid> TesterId { get; set; }

    public System.Guid State { get; set; }

    public bool IsRemoved { get; set; }

    public int NumberTask { get; set; }



    public virtual Employee Performer { get; set; }

    public virtual Employee Tester { get; set; }

    public virtual Project Project { get; set; }

    public virtual TaskState TaskState { get; set; }

}

}
