
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SUP.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Vacation
{

    public System.Guid Id { get; set; }

    public System.Guid EmployeeId { get; set; }

    public System.DateTime DateStart { get; set; }

    public System.DateTime DateEnd { get; set; }

    public string Comment { get; set; }

    public bool IsRemoved { get; set; }



    public virtual Employee Employee { get; set; }

}

}
